#!/usr/bin/with-contenv bash
## Prepare setup config
userdel netdata && groupdel netdata
rm -f /etc/ssmtp.conf && cp /defaults/ssmtp.conf /etc/ssmtp.conf

## Create config folders
declare -A dirs
dirs[ssmtp]="/etc/ssmtp"
folder="/config"

for key in "${!dirs[@]}"
do
        dir="$folder/$key"
        if [ ! -d "$dir" ]; then mv ${dirs[$key]} "$dir"; else rm -Rf ${dirs[$key]}; fi
        ln -s "$dir" ${dirs[$key]}
done

# Permissions
[ -f /var/run/docker.sock ] && chown abc.abc /var/run/docker.sock
chown -R abc.abc /config /opt/netdata
